export const skills = [
    {
        name:'WordPress',
        src:'wordpress.svg',
        color:'#21759b',
    },
    {
        name:'Next Js',
        src:'nextjs.svg',
        color:'#000000',
    },
    {
        name:'React',
        src:'react.svg',
        color:'#222222',
    },
    {
        name:'tailwind',
        src:'tailwind.svg',
        color:'#ffffff',
    },
    {
        name:'NodeJs',
        src:'nodejs.svg',
        color:'#f2f2f2',
    },
    {
        name:'PHP',
        src:'php.svg',
        color:'#8993be',
    },
    {
        name:'figma',
        src:'figma.svg',
        color:'#1e1e1e',
    },
    {
        name:'JavaScript',
        src:'js.svg',
        color:'#f0db4f',
    },
    {
        name:'vitejs',
        src:'vitejs.svg',
        color:'#363c42',
    },
    {
        name:'mysql',
        src:'mysql.svg',
        color:'#428db2',
    },
    {
        name:'MongoDB',
        src:'mongodb.svg',
        color:'#ffffff',
    },
    {
        name:'sass',
        src:'sass.svg',
        color:'#cd669a',
    },

]